type:
  namespace: &Namespace cyberdog
  simulator: &Simulator True

data:
  bringup_test:
    namespace: *Namespace
    package: cyberdog_bringup_test
    executable: cyberdog_bringup_test
    name: bringup_test
    exec_name: bringup_test
    parameters:
      - {simulator: *Simulator,                         description: "是否开启模拟器模式"}
      - {parameters_bool: True,               description: "bool 键值对"}
      - {parameters_int: 100,                   description: "int 键值对"}
      - {parameters_double: 0.1,              description: "double 键值对"}
      - {parameters_string0: string_message,  description: "string 键值对(单string):无引号方式约束"}
      - {parameters_string1: 'string message',description: "string 键值对(多string):单引号方式约束"}
      - {parameters_string2: "string message",description: "string 键值对(多string):双引号方式约束"}
      - {parameters_int_vector: [0,1,2,3,4,5,6,7,8,9],  description: "int 键值对(数组)"}
      - {parameters_double_vector: [0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],  description: "double 键值对(数组)"}
      - {parameters_bool_vector: [True,False,True,False,True,False,True,False,True,False],  description: "bool 键值对(数组)"}
      - {parameters_string_vector: [string,"string",'string',"string string",'string string',],  description: "string 键值对(数组)"}
      - {parameters_yaml: config.yaml,        description: "传入参数文件名称，由程序内部自行解析"}
      - {<include>: test.yaml,                description: "加载 cyberdog_bringup 包下参数文件内参数"}
      - {<include>: {package_name: cyberdog_bringup_test, config_path: parameters, yaml_name: config.yaml}, description: "加载 cyberdog_bringup_test 包参数文件内参数"}
    remappings:
      - {from: xxx1_topic,          to: xxx2_topic}
      - {from: xxx1_topic,          to: xxx3_topic}
      - {from: xxx1_service,        to: xxx2_service}
    arguments:
      - {bringup_argument_int: 0,             description: "int 键值对"}
      - {bringup_argument_float: 0.1,         description: "float 键值对"}
      - {bringup_argument_bool: True,         description: "bool 键值对"}
      - {bringup_argument_string: string, description: "string 键值对"}

  #------------------------------------------------------------->
  connector:
    namespace: *Namespace
    package: connector
    executable: connector

  #------------------------------------------------------------->
  device_manager:
    namespace: *Namespace
    package: device_manager
    executable: device_manager

  #------------------------------------------------------------->
  sensor_manager:
    namespace: *Namespace
    package: sensor_manager
    executable: sensor_manager

  #------------------------------------------------------------->
  cyberdog_manager:
    namespace: *Namespace
    package: cyberdog_manager
    executable: cyberdog_manager

  #------------------------------------------------------------->
  motion_manager:
    namespace: *Namespace
    package: black_box
    executable: black_box

  #------------------------------------------------------------->
  motion_manager:
    namespace: *Namespace
    package: motion_manager
    executable: motion_manager
